spring:
  application:
    name: onsure-web
  security:
    user:
      name: ${ONSURE_WEB_BOOTSTRAP_USER}
      password: ${ONSURE_WEB_BOOTSTRAP_PASSWORD}
  thymeleaf:
    cache: true

server:
  shutdown: graceful
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
